# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{rk.downloadAppImage}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab rk.downloadAppImage\cr
#' Type: \tab Package\cr
#' Version: \tab 0.01-0\cr
#' Date: \tab 2024-07-26\cr
#' Enhances: \tab rkward\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab https://rkward.kde.org\cr
#' }
#'
#' @title
#' \packageTitle{rk.downloadAppImage}
#' @author
#' \packageAuthor{rk.downloadAppImage}
#'
#' Maintainer: \packageMaintainer{rk.downloadAppImage}
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL